Blog.create!([
  {owner_id: 49, title: "music <3", description: "a blog for music lovers.", cover_photo: "http://res.cloudinary.com/kattelles/image/upload/v1467848796/rrf8ee5njpob14t4tueu.jpg"},
  {owner_id: 52, title: "My Travel Blog", description: "photos from my travels", cover_photo: "http://res.cloudinary.com/kattelles/image/upload/v1467994928/lo8nvi9i9fl9hmhqtmiv.jpg"},
  {owner_id: 50, title: "Quote of the Day", description: "a quote for every occasion", cover_photo: "http://res.cloudinary.com/kattelles/image/upload/v1467995585/b8bj7r447ycnnn5vxiuh.jpg"},
  {owner_id: 51, title: "Coding Rocks!", description: "tech and coding news", cover_photo: "http://res.cloudinary.com/kattelles/image/upload/v1467849747/tnba8uq7okv0dnqwkagd.jpg"},
  {owner_id: 53, title: "Kat's Blog", description: "creator of Stumblr", cover_photo: "https://res.cloudinary.com/kattelles/image/upload/v1467249835/elusive_pineapples_msnx7m.png"},
  {owner_id: 45, title: "my super cool blog!", description: "pineapples are the best :)", cover_photo: "https://res.cloudinary.com/kattelles/image/upload/v1467249835/elusive_pineapples_msnx7m.png"},
  {owner_id: 46, title: "san fran fan!", description: "all things san francisco.", cover_photo: "http://res.cloudinary.com/kattelles/image/upload/v1467847803/ubyjl5nf7tupohbo72n1.jpg"},
  {owner_id: 47, title: "I <3 Cats!", description: "cats are the best", cover_photo: "http://res.cloudinary.com/kattelles/image/upload/v1467848026/c3jrk1igdsl4nd7nbfom.jpg"},
  {owner_id: 48, title: "nature lover", description: "all things nature.", cover_photo: "http://res.cloudinary.com/kattelles/image/upload/v1467848420/cboqzynxoqrrrrykthq7.jpg"}
])
Follow.create!([
  {user_id: 47, blog_id: 41},
  {user_id: 52, blog_id: 44},
  {user_id: 52, blog_id: 45},
  {user_id: 52, blog_id: 46},
  {user_id: 52, blog_id: 41},
  {user_id: 52, blog_id: 42},
  {user_id: 52, blog_id: 43},
  {user_id: 50, blog_id: 44},
  {user_id: 50, blog_id: 46},
  {user_id: 50, blog_id: 45},
  {user_id: 50, blog_id: 41},
  {user_id: 50, blog_id: 42},
  {user_id: 50, blog_id: 43},
  {user_id: 51, blog_id: 44},
  {user_id: 51, blog_id: 45},
  {user_id: 51, blog_id: 41},
  {user_id: 51, blog_id: 42},
  {user_id: 51, blog_id: 43},
  {user_id: 49, blog_id: 45},
  {user_id: 49, blog_id: 46},
  {user_id: 49, blog_id: 41},
  {user_id: 49, blog_id: 42},
  {user_id: 49, blog_id: 43},
  {user_id: 47, blog_id: 46},
  {user_id: 47, blog_id: 45},
  {user_id: 47, blog_id: 44},
  {user_id: 47, blog_id: 43},
  {user_id: 53, blog_id: 44},
  {user_id: 53, blog_id: 45},
  {user_id: 53, blog_id: 46},
  {user_id: 53, blog_id: 41},
  {user_id: 53, blog_id: 42},
  {user_id: 53, blog_id: 43},
  {user_id: 46, blog_id: 48},
  {user_id: 47, blog_id: 48},
  {user_id: 48, blog_id: 48},
  {user_id: 50, blog_id: 48},
  {user_id: 51, blog_id: 48},
  {user_id: 52, blog_id: 48},
  {user_id: 45, blog_id: 40},
  {user_id: 45, blog_id: 48}
])
Like.create!([
  {user_id: 45, post_id: 138},
  {user_id: 45, post_id: 117},
  {user_id: 45, post_id: 108},
  {user_id: 45, post_id: 115},
  {user_id: 45, post_id: 112},
  {user_id: 47, post_id: 115},
  {user_id: 47, post_id: 112},
  {user_id: 48, post_id: 117},
  {user_id: 45, post_id: 139},
  {user_id: 45, post_id: 139},
  {user_id: 45, post_id: 121},
  {user_id: 45, post_id: 139},
  {user_id: 45, post_id: 139},
  {user_id: 45, post_id: 139},
  {user_id: 45, post_id: 139},
  {user_id: 45, post_id: 139},
  {user_id: 45, post_id: 119},
  {user_id: 45, post_id: 123},
  {user_id: 45, post_id: 142},
  {user_id: 45, post_id: 153},
  {user_id: 45, post_id: 154},
  {user_id: 45, post_id: 128},
  {user_id: 45, post_id: 165},
  {user_id: 45, post_id: 113},
  {user_id: 45, post_id: 116},
  {user_id: 45, post_id: 158},
  {user_id: 50, post_id: 137},
  {user_id: 50, post_id: 136},
  {user_id: 50, post_id: 135},
  {user_id: 50, post_id: 138},
  {user_id: 50, post_id: 169},
  {user_id: 50, post_id: 168},
  {user_id: 50, post_id: 167},
  {user_id: 50, post_id: 166},
  {user_id: 50, post_id: 163},
  {user_id: 50, post_id: 134},
  {user_id: 50, post_id: 132},
  {user_id: 50, post_id: 133},
  {user_id: 50, post_id: 131},
  {user_id: 50, post_id: 128},
  {user_id: 50, post_id: 127},
  {user_id: 50, post_id: 126},
  {user_id: 50, post_id: 125},
  {user_id: 50, post_id: 124},
  {user_id: 50, post_id: 123},
  {user_id: 50, post_id: 122},
  {user_id: 50, post_id: 121},
  {user_id: 50, post_id: 120},
  {user_id: 50, post_id: 116},
  {user_id: 50, post_id: 115},
  {user_id: 50, post_id: 114},
  {user_id: 50, post_id: 113},
  {user_id: 50, post_id: 112},
  {user_id: 45, post_id: 137},
  {user_id: 45, post_id: 136},
  {user_id: 51, post_id: 177},
  {user_id: 51, post_id: 176},
  {user_id: 51, post_id: 169},
  {user_id: 51, post_id: 168},
  {user_id: 51, post_id: 166},
  {user_id: 51, post_id: 138},
  {user_id: 51, post_id: 137},
  {user_id: 51, post_id: 135},
  {user_id: 51, post_id: 134},
  {user_id: 51, post_id: 132},
  {user_id: 51, post_id: 133},
  {user_id: 51, post_id: 126},
  {user_id: 51, post_id: 127},
  {user_id: 51, post_id: 128},
  {user_id: 51, post_id: 125},
  {user_id: 51, post_id: 124},
  {user_id: 51, post_id: 123},
  {user_id: 51, post_id: 122},
  {user_id: 51, post_id: 121},
  {user_id: 51, post_id: 120},
  {user_id: 51, post_id: 116},
  {user_id: 51, post_id: 115},
  {user_id: 51, post_id: 114},
  {user_id: 51, post_id: 112},
  {user_id: 51, post_id: 113},
  {user_id: 49, post_id: 181},
  {user_id: 49, post_id: 180},
  {user_id: 49, post_id: 179},
  {user_id: 49, post_id: 178},
  {user_id: 49, post_id: 177},
  {user_id: 49, post_id: 176},
  {user_id: 49, post_id: 169},
  {user_id: 49, post_id: 168},
  {user_id: 49, post_id: 167},
  {user_id: 49, post_id: 166},
  {user_id: 49, post_id: 138},
  {user_id: 49, post_id: 137},
  {user_id: 49, post_id: 136},
  {user_id: 49, post_id: 135},
  {user_id: 49, post_id: 123},
  {user_id: 49, post_id: 122},
  {user_id: 49, post_id: 121},
  {user_id: 49, post_id: 120},
  {user_id: 49, post_id: 116},
  {user_id: 49, post_id: 115},
  {user_id: 49, post_id: 114},
  {user_id: 49, post_id: 113},
  {user_id: 49, post_id: 112},
  {user_id: 47, post_id: 181},
  {user_id: 47, post_id: 180},
  {user_id: 47, post_id: 179},
  {user_id: 47, post_id: 178},
  {user_id: 47, post_id: 177},
  {user_id: 47, post_id: 176},
  {user_id: 47, post_id: 169},
  {user_id: 47, post_id: 168},
  {user_id: 47, post_id: 167},
  {user_id: 47, post_id: 166},
  {user_id: 47, post_id: 138},
  {user_id: 47, post_id: 137},
  {user_id: 47, post_id: 136},
  {user_id: 47, post_id: 134},
  {user_id: 47, post_id: 135},
  {user_id: 47, post_id: 133},
  {user_id: 47, post_id: 132},
  {user_id: 47, post_id: 131},
  {user_id: 47, post_id: 128},
  {user_id: 47, post_id: 127},
  {user_id: 47, post_id: 126},
  {user_id: 47, post_id: 125},
  {user_id: 47, post_id: 124},
  {user_id: 47, post_id: 123},
  {user_id: 47, post_id: 122},
  {user_id: 47, post_id: 121},
  {user_id: 47, post_id: 120},
  {user_id: 47, post_id: 114},
  {user_id: 47, post_id: 113},
  {user_id: 53, post_id: 185},
  {user_id: 53, post_id: 184},
  {user_id: 53, post_id: 183},
  {user_id: 53, post_id: 182},
  {user_id: 53, post_id: 181},
  {user_id: 53, post_id: 179},
  {user_id: 53, post_id: 180},
  {user_id: 53, post_id: 178},
  {user_id: 53, post_id: 177},
  {user_id: 53, post_id: 176},
  {user_id: 53, post_id: 168},
  {user_id: 53, post_id: 169},
  {user_id: 53, post_id: 167},
  {user_id: 53, post_id: 166},
  {user_id: 53, post_id: 138},
  {user_id: 53, post_id: 137},
  {user_id: 53, post_id: 136},
  {user_id: 53, post_id: 135},
  {user_id: 53, post_id: 134},
  {user_id: 53, post_id: 133},
  {user_id: 53, post_id: 132},
  {user_id: 53, post_id: 131},
  {user_id: 53, post_id: 128},
  {user_id: 53, post_id: 127},
  {user_id: 53, post_id: 126},
  {user_id: 53, post_id: 125},
  {user_id: 53, post_id: 124},
  {user_id: 53, post_id: 123},
  {user_id: 53, post_id: 122},
  {user_id: 53, post_id: 121},
  {user_id: 53, post_id: 120},
  {user_id: 53, post_id: 116},
  {user_id: 53, post_id: 115},
  {user_id: 53, post_id: 114},
  {user_id: 53, post_id: 113},
  {user_id: 53, post_id: 112},
  {user_id: 46, post_id: 196},
  {user_id: 46, post_id: 195},
  {user_id: 46, post_id: 194},
  {user_id: 46, post_id: 193},
  {user_id: 46, post_id: 192},
  {user_id: 46, post_id: 191},
  {user_id: 46, post_id: 190},
  {user_id: 46, post_id: 189},
  {user_id: 46, post_id: 188},
  {user_id: 46, post_id: 187},
  {user_id: 46, post_id: 186},
  {user_id: 47, post_id: 196},
  {user_id: 47, post_id: 195},
  {user_id: 47, post_id: 194},
  {user_id: 47, post_id: 193},
  {user_id: 47, post_id: 192},
  {user_id: 47, post_id: 191},
  {user_id: 47, post_id: 190},
  {user_id: 47, post_id: 189},
  {user_id: 47, post_id: 188},
  {user_id: 47, post_id: 187},
  {user_id: 47, post_id: 186},
  {user_id: 48, post_id: 196},
  {user_id: 48, post_id: 195},
  {user_id: 48, post_id: 194},
  {user_id: 48, post_id: 193},
  {user_id: 48, post_id: 192},
  {user_id: 48, post_id: 191},
  {user_id: 48, post_id: 190},
  {user_id: 48, post_id: 189},
  {user_id: 48, post_id: 188},
  {user_id: 48, post_id: 187},
  {user_id: 48, post_id: 186},
  {user_id: 50, post_id: 195},
  {user_id: 50, post_id: 196},
  {user_id: 50, post_id: 192},
  {user_id: 50, post_id: 191},
  {user_id: 50, post_id: 190},
  {user_id: 50, post_id: 189},
  {user_id: 50, post_id: 188},
  {user_id: 50, post_id: 186},
  {user_id: 51, post_id: 185},
  {user_id: 51, post_id: 184},
  {user_id: 51, post_id: 183},
  {user_id: 51, post_id: 182},
  {user_id: 51, post_id: 196},
  {user_id: 51, post_id: 195},
  {user_id: 51, post_id: 194},
  {user_id: 51, post_id: 193},
  {user_id: 51, post_id: 192},
  {user_id: 51, post_id: 191},
  {user_id: 51, post_id: 190},
  {user_id: 51, post_id: 189},
  {user_id: 51, post_id: 188},
  {user_id: 51, post_id: 187},
  {user_id: 51, post_id: 186},
  {user_id: 52, post_id: 185},
  {user_id: 52, post_id: 184},
  {user_id: 52, post_id: 183},
  {user_id: 52, post_id: 182},
  {user_id: 52, post_id: 181},
  {user_id: 52, post_id: 180},
  {user_id: 52, post_id: 179},
  {user_id: 52, post_id: 178},
  {user_id: 52, post_id: 177},
  {user_id: 52, post_id: 176},
  {user_id: 52, post_id: 196},
  {user_id: 52, post_id: 195},
  {user_id: 52, post_id: 194},
  {user_id: 52, post_id: 193},
  {user_id: 52, post_id: 192},
  {user_id: 52, post_id: 191},
  {user_id: 52, post_id: 190},
  {user_id: 52, post_id: 189},
  {user_id: 52, post_id: 188},
  {user_id: 52, post_id: 187},
  {user_id: 52, post_id: 186},
  {user_id: 45, post_id: 169},
  {user_id: 45, post_id: 195},
  {user_id: 45, post_id: 194},
  {user_id: 45, post_id: 182},
  {user_id: 45, post_id: 188}
])
Post.create!([
  {user_id: 46, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: "http://travel.usnews.com/San_Francisco_CA/Things_To_Do/", post_type: "Link", audio_url: nil, video_url: nil, image_caption: nil, link_title: "Best Things to Do in SF!", audio_title: nil, video_title: nil},
  {user_id: 46, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467847627/d4dsxifkmzp2izvjvzje.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 48, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467848534/dy8qz8hfnchw5pjneby8.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 48, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467848552/gqbrjf5wdkzql942umrj.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 48, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467848566/xjdevsclmvnfmzhu4ubr.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 48, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467848580/ibphbyfqwmr0yrzqpwvw.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 49, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Audio", audio_url: "http://res.cloudinary.com/kattelles/video/upload/v1467669560/01_Take_Me_to_Church_nmkoun.m4a", video_url: nil, image_caption: nil, link_title: nil, audio_title: "Take Me To Church by Hozier", video_title: nil},
  {user_id: 49, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Audio", audio_url: "http://res.cloudinary.com/kattelles/video/upload/v1467848910/10_Somewhere_Over_the_Rainbow_jkzwvy.m4a", video_url: nil, image_caption: nil, link_title: nil, audio_title: "Somewhere Over the Rainbow", video_title: nil},
  {user_id: 49, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Audio", audio_url: "http://res.cloudinary.com/kattelles/video/upload/v1467848928/11_Follow_Your_Arrow_h9i1wv.m4a", video_url: nil, image_caption: nil, link_title: nil, audio_title: "Follow Your Arrow by Kacey Musgraves", video_title: nil},
  {user_id: 49, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Audio", audio_url: "http://res.cloudinary.com/kattelles/video/upload/v1467848939/01_Welcome_To_New_York_nb5fpo.m4a", video_url: nil, image_caption: nil, link_title: nil, audio_title: "Welcome to New York by Taylor Swift", video_title: nil},
  {user_id: 49, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Audio", audio_url: "http://res.cloudinary.com/kattelles/video/upload/v1467848958/Pointer_Sisters_Jump_kfd4ip.mp3", video_url: nil, image_caption: nil, link_title: nil, audio_title: "Jump by the Pointer Sisters", video_title: nil},
  {user_id: 49, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Audio", audio_url: "http://res.cloudinary.com/kattelles/video/upload/v1467848986/Karmin_-_Hello_vvgyit.mp3", video_url: nil, image_caption: nil, link_title: nil, audio_title: "Hello by Karmin", video_title: nil},
  {user_id: 49, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Audio", audio_url: "http://res.cloudinary.com/kattelles/video/upload/v1467848970/Wake_Me_Up_--_Avicii_ft._Aloe_Blacc_Lyrics_c8ehuw.mp3", video_url: nil, image_caption: nil, link_title: nil, audio_title: "Wake Me Up by Avicii", video_title: nil},
  {user_id: 50, title: nil, content: nil, image_url: nil, quote: "I never said most of the things I said.", quote_source: "Yogi Berra", link_url: nil, post_type: "Quote", audio_url: nil, video_url: nil, image_caption: nil, link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 50, title: nil, content: nil, image_url: nil, quote: "It is not in the stars to hold our destiny but in ourselves. ", quote_source: "William Shakespeare", link_url: nil, post_type: "Quote", audio_url: nil, video_url: nil, image_caption: nil, link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 50, title: nil, content: nil, image_url: nil, quote: "What we think, we become.", quote_source: "Buddha", link_url: nil, post_type: "Quote", audio_url: nil, video_url: nil, image_caption: nil, link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 50, title: nil, content: nil, image_url: nil, quote: "You can't depend on your eyes when your imagination is out of focus. ", quote_source: "Mark Twain", link_url: nil, post_type: "Quote", audio_url: nil, video_url: nil, image_caption: nil, link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 45, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467916737/y3aydkkmtt86sxpcg5z7.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 48, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467994632/dxdci49zsgik7fiyzhjv.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 45, title: "my first stumblr post!", content: "hello, world! ", image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Text", audio_url: nil, video_url: nil, image_caption: nil, link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 48, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467994676/paff3j7tjnwzze13ap9k.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 45, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467846179/knq51xhcazsp0ysijdhe.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "cats are silly", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 48, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467994587/zhxbzclmep6kyrpuqh9c.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 46, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467847676/vqamzz88iecvudxardur.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 46, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Video", audio_url: nil, video_url: "https://www.youtube.com/watch?v=SLeBvceHRWY", image_caption: nil, link_title: nil, audio_title: nil, video_title: ""},
  {user_id: 46, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: "https://www.sfbike.org/resources/maps-routes/", post_type: "Link", audio_url: nil, video_url: nil, image_caption: nil, link_title: "Bike SF! :)", audio_title: nil, video_title: nil},
  {user_id: 52, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467995185/tknzamdsvyfjhdftszjq.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 52, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467995210/qfsbczbcqnanfbmxanxh.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 52, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467995234/x3rrloglu41swiamt3gg.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 52, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467995259/ucpduyp0zoppky9iqsxq.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 52, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467995292/lue97cn1vkeegv39p08g.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 52, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467995314/qrkbt2mumknfius3pgyr.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 50, title: nil, content: nil, image_url: nil, quote: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. ", quote_source: "Maya Angelou", link_url: nil, post_type: "Quote", audio_url: nil, video_url: nil, image_caption: nil, link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 50, title: nil, content: nil, image_url: nil, quote: "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence. ", quote_source: "Confusius", link_url: nil, post_type: "Quote", audio_url: nil, video_url: nil, image_caption: nil, link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 51, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467996142/d6grr2eywuoac8itjvcq.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 51, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: "https://techcrunch.com/2016/07/08/where-todays-tech-can-and-cant-replace-humans/", post_type: "Link", audio_url: nil, video_url: nil, image_caption: nil, link_title: "Where today’s tech can, and can’t, replace humans", audio_title: nil, video_title: nil},
  {user_id: 51, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: "https://techcrunch.com/2016/07/07/how-berlin-can-become-europes-no-1-tech-hub/", post_type: "Link", audio_url: nil, video_url: nil, image_caption: nil, link_title: "How Berlin can become Europe’s No. 1 tech hub", audio_title: nil, video_title: nil},
  {user_id: 51, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Video", audio_url: nil, video_url: "https://www.youtube.com/watch?v=mMUTJtugdmw", image_caption: nil, link_title: nil, audio_title: nil, video_title: "Apps for planning your summer vacation"},
  {user_id: 49, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Video", audio_url: nil, video_url: "https://www.youtube.com/watch?v=Zi_XLOBDo_Y", image_caption: nil, link_title: nil, audio_title: nil, video_title: ""},
  {user_id: 49, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Video", audio_url: nil, video_url: "https://www.youtube.com/watch?v=tUG5atZoHtQ", image_caption: nil, link_title: nil, audio_title: nil, video_title: ""},
  {user_id: 47, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Video", audio_url: nil, video_url: "https://www.youtube.com/watch?v=SaA_cs4WZHM", image_caption: nil, link_title: nil, audio_title: nil, video_title: ""},
  {user_id: 47, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467996774/x3ksf4fazf6czzjse9nl.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 47, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467996784/ac6rzuibux1kzlwqoqo6.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 47, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Video", audio_url: nil, video_url: "https://www.youtube.com/watch?v=G8KpPw303PY", image_caption: nil, link_title: nil, audio_title: nil, video_title: "Funny Cats"},
  {user_id: 53, title: "Welcome to Stumblr!", content: "hey there, world.", image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Text", audio_url: nil, video_url: nil, image_caption: nil, link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 47, title: nil, content: nil, image_url: nil, quote: "'Meow means 'woof' in cat.", quote_source: "George Carlin", link_url: nil, post_type: "Quote", audio_url: nil, video_url: nil, image_caption: nil, link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 53, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467997139/hz2p4sleubngjls1hqje.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 53, title: nil, content: nil, image_url: nil, quote: nil, quote_source: nil, link_url: "https://www.appacademy.io/", post_type: "Link", audio_url: nil, video_url: nil, image_caption: nil, link_title: "app academy", audio_title: nil, video_title: nil},
  {user_id: 53, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467997364/qif2ccbn0unswf9na67a.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "@fort funston", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 45, title: "stumblr > tumblr ", content: "I love this app!", image_url: nil, quote: nil, quote_source: nil, link_url: nil, post_type: "Text", audio_url: nil, video_url: nil, image_caption: nil, link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 53, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467997423/v0p2afikosbeegi6ethn.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "silly puppy", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 53, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467997439/idqa4fdqjvjdlzdtowgr.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 53, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467997473/ai7yncorivpr3pwszfce.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "@new brighton beach", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 53, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467997594/hcxgdypcqehcxxtnf1g5.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "Madrid, Spain", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 53, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467997624/ukxuw0i8goujihmkxkmd.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "Edinburgh, Scotland", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 53, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467997653/ll8tmpkjiarobj9kyfre.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "Treasure Island", link_title: nil, audio_title: nil, video_title: nil},
  {user_id: 53, title: nil, content: nil, image_url: "http://res.cloudinary.com/kattelles/image/upload/v1467997690/fzoouugdzgqc8rainb80.jpg", quote: nil, quote_source: nil, link_url: nil, post_type: "Image", audio_url: nil, video_url: nil, image_caption: "Rome", link_title: nil, audio_title: nil, video_title: nil}
])
Tag.create!([
  {name: "winning?"},
  {name: "cool"},
  {name: "dogs"},
  {name: "silly"},
  {name: "link"},
  {name: "test"},
  {name: "tags"},
  {name: "ats"},
  {name: "pugs"},
  {name: "#coding"},
  {name: "#news"},
  {name: "cats"},
  {name: "coding"},
  {name: "news"},
  {name: "funny"},
  {name: "tech"},
  {name: "happy"},
  {name: "animals"},
  {name: "fish"},
  {name: "nature"},
  {name: "music"},
  {name: "deadhead"},
  {name: "photo"},
  {name: "california"},
  {name: "SF"},
  {name: "travel"},
  {name: "biking"},
  {name: "quote"},
  {name: "robots"},
  {name: "welcome"},
  {name: "bootcamp"},
  {name: "webdev"},
  {name: "camping"},
  {name: "scotland"}
])
Tagging.create!([
  {post_id: 123, tag_id: 34},
  {post_id: 122, tag_id: 34},
  {post_id: 121, tag_id: 34},
  {post_id: 120, tag_id: 34},
  {post_id: 154, tag_id: 1},
  {post_id: 122, tag_id: 37},
  {post_id: 121, tag_id: 37},
  {post_id: 120, tag_id: 37},
  {post_id: 166, tag_id: 38},
  {post_id: 166, tag_id: 37},
  {post_id: 166, tag_id: 34},
  {post_id: 167, tag_id: 34},
  {post_id: 167, tag_id: 37},
  {post_id: 168, tag_id: 34},
  {post_id: 115, tag_id: 39},
  {post_id: 114, tag_id: 39},
  {post_id: 114, tag_id: 40},
  {post_id: 113, tag_id: 39},
  {post_id: 112, tag_id: 39},
  {post_id: 112, tag_id: 40},
  {post_id: 169, tag_id: 39},
  {post_id: 169, tag_id: 40},
  {post_id: 169, tag_id: 41},
  {post_id: 170, tag_id: 40},
  {post_id: 171, tag_id: 40},
  {post_id: 172, tag_id: 40},
  {post_id: 173, tag_id: 40},
  {post_id: 174, tag_id: 40},
  {post_id: 175, tag_id: 40},
  {post_id: 175, tag_id: 37},
  {post_id: 174, tag_id: 37},
  {post_id: 173, tag_id: 37},
  {post_id: 172, tag_id: 37},
  {post_id: 138, tag_id: 42},
  {post_id: 137, tag_id: 42},
  {post_id: 136, tag_id: 42},
  {post_id: 134, tag_id: 22},
  {post_id: 134, tag_id: 23},
  {post_id: 134, tag_id: 19},
  {post_id: 134, tag_id: 24},
  {post_id: 135, tag_id: 42},
  {post_id: 176, tag_id: 42},
  {post_id: 177, tag_id: 42},
  {post_id: 178, tag_id: 29},
  {post_id: 178, tag_id: 27},
  {post_id: 178, tag_id: 30},
  {post_id: 154, tag_id: 26},
  {post_id: 179, tag_id: 30},
  {post_id: 179, tag_id: 43},
  {post_id: 179, tag_id: 28},
  {post_id: 180, tag_id: 30},
  {post_id: 180, tag_id: 28},
  {post_id: 180, tag_id: 40},
  {post_id: 181, tag_id: 30},
  {post_id: 181, tag_id: 40},
  {post_id: 134, tag_id: 35},
  {post_id: 133, tag_id: 35},
  {post_id: 132, tag_id: 35},
  {post_id: 131, tag_id: 35},
  {post_id: 128, tag_id: 35},
  {post_id: 127, tag_id: 35},
  {post_id: 154, tag_id: 32},
  {post_id: 126, tag_id: 35},
  {post_id: 125, tag_id: 35},
  {post_id: 124, tag_id: 35},
  {post_id: 109, tag_id: 26},
  {post_id: 109, tag_id: 6},
  {post_id: 109, tag_id: 29},
  {post_id: 116, tag_id: 26},
  {post_id: 116, tag_id: 29},
  {post_id: 182, tag_id: 26},
  {post_id: 183, tag_id: 26},
  {post_id: 184, tag_id: 26},
  {post_id: 184, tag_id: 29},
  {post_id: 184, tag_id: 32},
  {post_id: 185, tag_id: 26},
  {post_id: 185, tag_id: 29},
  {post_id: 185, tag_id: 42},
  {post_id: 186, tag_id: 44},
  {post_id: 187, tag_id: 4},
  {post_id: 187, tag_id: 32},
  {post_id: 188, tag_id: 27},
  {post_id: 188, tag_id: 45},
  {post_id: 188, tag_id: 46},
  {post_id: 189, tag_id: 4},
  {post_id: 189, tag_id: 34},
  {post_id: 189, tag_id: 39},
  {post_id: 190, tag_id: 4},
  {post_id: 190, tag_id: 47},
  {post_id: 191, tag_id: 4},
  {post_id: 191, tag_id: 6},
  {post_id: 191, tag_id: 32},
  {post_id: 192, tag_id: 4},
  {post_id: 192, tag_id: 32},
  {post_id: 188, tag_id: 39},
  {post_id: 193, tag_id: 40},
  {post_id: 193, tag_id: 37},
  {post_id: 194, tag_id: 40},
  {post_id: 194, tag_id: 48},
  {post_id: 195, tag_id: 39},
  {post_id: 195, tag_id: 40},
  {post_id: 196, tag_id: 40},
  {post_id: 196, tag_id: 37},
  {post_id: 197, tag_id: 30}
])
User.create!([
  {username: "guest", password_digest: "$2a$10$oCZ3/ufxZ2WtVT8rgixl..cOMWbaES6FIC85x.7xB9h1r.YEEmExa", session_token: "m6UymqHNQWP+E2hwjY2bpA==", avatar: "https://res.cloudinary.com/kattelles/image/upload/v1467250036/tumblr_o51oavbMDx1ugpbmuo7_500_2_rpuo6x.png"},
  {username: "cats>dogs", password_digest: "$2a$10$q2ojECxIbkdNYg3bXu4uW.D1ZEalVtXUFbNRQeVqgUjPLu0tHUfni", session_token: "P+H9ZcPZZRWIcOZ2YPjD+g==", avatar: "http://res.cloudinary.com/kattelles/image/upload/v1467848064/hdu8d6suu9dngvkv6wl3.jpg"},
  {username: "nature_lover", password_digest: "$2a$10$wVScrH7qVBTXgm/GKJEEMeNuS9qToXtANDfvFA.DogsT7hmxC.dKi", session_token: "jwAAAdblO5XKqmtmcHLw3w==", avatar: "http://res.cloudinary.com/kattelles/image/upload/v1467848333/cbr6vo3hcgasv0ewr8ib.jpg"},
  {username: "quoteoftheday", password_digest: "$2a$10$wtu0/3IM3FEFc8KPtY5JKuYJ85EM/qYgT5ZmWN7cmjZZ6IX5UQxjC", session_token: "z6PsFpQ85ZNgCSDwhvWaXQ==", avatar: "http://res.cloudinary.com/kattelles/image/upload/v1467995397/gxwcinyqwksqmf41qvu0.jpg"},
  {username: "coding_rocks", password_digest: "$2a$10$/czdtkLrRLjngxlDT/25TeGJKRICPSMeiDtUyHkKS9O5EfRUcZnW6", session_token: "hZWDXEOM6/SQ/jR83kePag==", avatar: "http://res.cloudinary.com/kattelles/image/upload/v1467849709/mn0le2iaarptn7pjbbii.png"},
  {username: "musiclover", password_digest: "$2a$10$kFlq.JiwomR8PAeC17RprOv3MvYpiexnyFhc6JATtsXltJ1C5uRRC", session_token: "+LP/uLLwaTXBP0qJdZAwGA==", avatar: "http://res.cloudinary.com/kattelles/image/upload/v1467848868/qnoievydmn0rjn81b83l.png"},
  {username: "travel", password_digest: "$2a$10$hzIErk1hZfeRIgVpk4nG5.n0jddc1/l3hF84bObpw0O8i6.ZLiVfi", session_token: "HBzXDXz5EQRxAIZ8meGuKA==", avatar: "http://res.cloudinary.com/kattelles/image/upload/v1467994971/ajaavo4dd4yhkdsx5ubd.png"},
  {username: "kat", password_digest: "$2a$10$OLh1H0UGx4qlvuQJRDA8nOrrCN0kfYwAbWQjTSlpKWdvlJf5pHXcC", session_token: "rZYscAta4FdLEIjmX8L+mw==", avatar: "http://res.cloudinary.com/kattelles/image/upload/v1467997037/j8fpc9bzbsq8iv7zs4sb.png"},
  {username: "sanfran", password_digest: "$2a$10$KguXo8SlEov7q6CYhCG22exvh0T5GsWgEdEND0l2i0HKaFr7YVEye", session_token: "ZKJ9SHfH6jhsZy+zxhV71A==", avatar: "http://res.cloudinary.com/kattelles/image/upload/v1467847884/cmz8vbpuwddbmwofnf6b.gif"}
])
